/**
 * Deterministic per-slot diversity hints — large pools, soft wording for LLM.
 * Does not change GPU contract; only enriches planner/renderer user prompts.
 */

import { sha256Hex } from '../lib/idempotency.js';

export type DiversityMode = 'off' | 'soft' | 'full';

/** Normalize env / caller string to a DiversityMode. */
export function parseDiversityMode(raw: string | undefined): DiversityMode {
  const m = (raw ?? 'soft').toLowerCase().trim();
  if (m === 'off' || m === '0' || m === 'false') return 'off';
  if (m === 'full' || m === 'strong') return 'full';
  return 'soft';
}

export interface SlotHints {
  /** Passed to planner as creative anchors (natural language). */
  plannerLines: string;
  /** Passed to renderer for first-frame / composition emphasis. */
  rendererFrameEmphasis: string;
}

/** Scene flavour: broad buckets, many variants — LLM interprets loosely. */
const SCENE_ARCHETYPE_HINTS: string[] = [
  'Busy urban sidewalk at rush hour, single clear subject',
  'Quiet suburban front porch in late afternoon',
  'Crowded weekend farmers market aisle',
  'Empty early-morning swimming pool deck',
  'Small apartment kitchen during meal prep chaos',
  'Open-plan office after hours, desk lamps only',
  'Rain-streaked bus window from inside the vehicle',
  'Sunny rooftop garden with planters and city behind',
  'Dim basement workshop with a single task lamp',
  'Bright laundromat row of machines humming',
  'Coastal boardwalk with wind and distant gulls',
  'Snowy residential street, footprints only',
  'Hospital corridor calm moment, no crowd',
  'School hallway lockers, between classes',
  'Museum gallery sparse visitors, one painting focus',
  'Construction site edge, safety gear visible',
  'Night convenience store glow from outside',
  'Train platform empty except one figure',
  'Bike repair stand in a cluttered garage',
  'Florist shop cooler mist and colour stacks',
  'Barber chair mirror reflection dominant',
  'Yoga studio mirrors and bare walls',
  'Climbing gym textured wall and chalk dust',
  'Skate park concrete curves, late sun',
  'Dog park fence line and grass wear',
  'Riverbank mud and reeds, wading depth',
  'Campfire ring with ember light only',
  'Greenhouse humidity and glass panels',
  'Stables aisle straw and horse silhouette',
  'Airport gate seating rows, delayed calm',
  'Hotel hallway carpet pattern leading away',
  'Elevator interior metallic and tight',
  'Parking garage pillar rhythm and echo',
  'Alley dumpster side, graffiti texture',
  'Fire escape landing urban texture',
  'Bookstore aisle tight shelves',
  'Record shop crate-digging posture',
  'Pharmacy aisle clinical lighting',
  'Hardware store aisle tools wall',
  'Fabric store bolt rolls colour chaos',
  'Butcher shop case glass and steam',
  'Fish market ice bed and scale',
  'Temple courtyard incense haze subtle',
  'Church pew row low winter light',
  'Mosque courtyard fountain edge',
  'Synagogue study table scattered books',
  'Community centre gymnasium lines',
  'Bowling lane approach and pins',
  'Arcade cabinet glow on faces',
  'Diner booth vinyl and chrome edge',
  'Food truck service window steam',
  'Night food stall wok flare',
  'Beach towel patch crowded summer',
  'Desert road heat shimmer single car',
  'Mountain trail switchback dust',
  'Forest trail fern close and trunks',
  'Vineyard row vanishing point',
  'Orchard blossom fall gentle',
  'Greenhouse seedling trays macro context',
  'Factory floor machine rhythm background',
  'Shipping warehouse aisle boxes tall',
  'Courier sorting table scan lights',
  'Library reading room whisper hush',
  'University quad stone and bikes',
  'Playground swing set empty swing',
  'Basketball court chain net clank',
  'Soccer field corner flag wind',
  'Tennis court line geometry harsh sun',
  'Pool table felt and overhead lamp',
  'Bowling shoe rental counter clutter',
  'Ice rink boards and breath fog',
  'Ski lodge boot room damp gear',
  'Surf lineup waiting set wave',
  'Kayak put-in muddy bank',
  'Dock cleat rope coil close',
  'Canal house step bike leaning',
  'Cobblestone square fountain off',
  'Outdoor café umbrella shade pattern',
  'Night market lantern string bokeh',
  'Subway car pole grip strap sway',
  'Ferry deck railing spray mist',
  'Cable car cabin window tilt',
  'Cable-stayed bridge walkway wind',
  'Observation wheel cabin slow rise',
  'Zoo enclosure glass reflection visitor',
  'Aquarium tunnel blue silhouette',
  'Planetarium dome star projection wash',
  'Science museum interactive table hands',
  'Kids museum colourful blocks scale',
  'Art studio paint splatter floor honest',
  'Pottery studio wheel splash frozen',
  'Jewellery bench visor and tweezers',
  'Tailor shop mannequin and pin cushion',
  'Shoe repair bench worn leather smell implied',
  'Watch repair loupe and tiny screws',
  'Vinyl pressing plant steam and label',
  'Screen print shop squeegee pause',
  'Darkroom red safe light tray',
  'Podcast closet foam panels tight',
  'Radio booth mic arm and pop filter',
  'News desk stack of scripts edge',
  'Weather green screen hand gesture',
  'Makeup chair ring light circle eyes',
  'Wardrobe rack garment plastic rustle',
  'Film set flat wooden false wall',
  'Concert backstage cable spaghetti',
  'Theatre wing velvet rope edge',
  'Orchestra pit stand lights low',
  'Street busker case coins glint',
  'Breakdance circle chalk dust kick',
  'Parade confetti ground swirl aftermath',
  'Protest crowd sign edge one face',
  'Marathon water table volunteer stretch',
  'Cyclist rest stop map unfold',
  'Motorcycle curb mount one boot',
  'Scooter charge dock LED stripe',
  'Electric car plug handle close',
  'Gas station nozzle click night',
  'Car wash foam arch colour',
  'Drive-through headset window reflection',
  'Parking meter coin twist detail',
  'Traffic island planter wind flowers',
  'Roundabout blur motion streak',
  'Crosswalk countdown frozen step',
  'Bike lane paint fresh white',
  'Scooter share pile tangle chrome',
  'Rollerblade path lake mirror',
  'Park bench pigeon negotiation',
  'Duck pond bread toss arc',
  'Kite string tension sky slice',
  'Frisbee disc spin catch freeze',
  'Basketball hoop chain net sun flare',
  'Soccer ball spin turf kick',
  'American football spiral tight spiral',
  'Volleyball sand dive stretch',
  'Badminton shuttle peak hang',
  'Table tennis paddle blur exchange',
  'Cricket bat follow through dust',
  'Golf swing divot spray honest',
  'Baseball mitt pop leather sound implied',
  'Hockey stick tape wear close',
  'Figure skate toe pick scratch',
  'Boxing bag chain sway sweat',
  'Jump rope arc rope blur',
  'Kettlebell swing hip hinge freeze',
  'Barbell rack clip collar glint',
  'Pull-up bar chalk hand hang',
  'Rowing machine slide seat end',
  'Treadmill belt texture foot plant',
  'Stair climber LED floor rhythm',
  'Medicine ball slam dust puff',
  'Battle rope wave peak freeze',
  'Punching mitts trainer gloves tap',
  'Stretch band door anchor tug',
  'Foam roller spine arch pause',
  'Massage table sheet fold corner',
  'Physical therapy step platform line',
  'Wheelchair ramp rain bead line',
  'White cane crosswalk tap freeze',
  'Guide dog harness handle tension',
  'Baby stroller wheel bump curb',
  'Shopping cart wheel wobble aisle',
  'Hand basket overflow checkout',
  'Self-checkout scanner beep pause',
  'Receipt printer curl paper edge',
  'ATMs in a row night glow',
  'Coin laundry cart sock mismatch',
  'Ironing board cover floral honest',
  'Vacuum cleaner cord loop floor',
  'Mop bucket wringer twist',
  'Broom dust pan line crisp',
  'Leaf blower dust cloud arc',
  'Snow shovel lift flake spray',
  'Garden hose coil mud honest',
  'Lawn mower stripe fresh cut',
  'Chainsaw chip spray safety gear',
  'Axe split log ring stall',
  'Camp axe kindling pile careful',
  'Fishing rod bend line tension',
  'Fly tie vise feather close',
  'Hunter orange vest forest edge',
  'Target range brass shell sparkle',
  'Archery release follow through',
  'Paintball mask breath fog',
  'Laser tag vest glow stripe',
  'Escape room lock dial fingers',
  'Board game table dice mid-roll',
  'Chess clock finger hover tense',
  'Poker table chip shuffle arc',
  'Domino chain first tile tip',
  'Jigsaw puzzle edge piece find',
  'Lego bin pour colour avalanche',
  'Model train loop tunnel mouth',
  'RC car ramp hang freeze',
  'Drone prop blur ground shadow',
  'Kite aerial reel hand tension',
  'Telescope eyepiece dim red',
  'Binoculars bird silhouette tree',
  'Metal detector beach sweep arc',
  'Magnet fishing canal splash pull',
  'Metal detector field coil hover',
];

/** Opening frame / composition — strong visual spread for first frame. */
const OPENING_FRAMING_HINTS: string[] = [
  'Open on an extreme close-up of texture before revealing context',
  'Start wide establishing then let subject enter frame edge',
  'Subject anchored lower third, lots of negative sky or ceiling',
  'Subject tight right frame, leading space left for motion',
  'Subject tight left frame, leading space right for motion',
  'Top-down table geometry, hands as secondary',
  'Low angle upward, subject dominant against sky or ceiling',
  'High angle downward, floor pattern as graphic background',
  'Through foreground obstruction: glass, fence, foliage partial',
  'Reflection-first: mirror, window, phone screen, or puddle',
  'Silhouette rim light, face detail minimal at start',
  'Backlit hair glow, face in softer fill',
  'Profile-only start, camera rolls to three-quarter',
  'Hands and object dominate; face optional or partial',
  'Object macro fills frame; human context implied off-edge',
  'Single point colour pop against muted surroundings',
  'Monochrome wall behind subject, shape reads clean',
  'Busy background but shallow depth isolates subject',
  'Deep focus: subject mid-ground, foreground element frames',
  'Dutch tilt subtle, energy without chaos',
  'Static camera, subject crosses through plane',
  'Camera slow push on eyes or object detail',
  'Camera slow pull to reveal wider situation',
  'Handheld micro-shake, documentary intimacy',
  'Tripod lock-off, performance in centre',
  'Over-shoulder insert into task, not face-forward',
  'POV hands reaching into frame centre',
  'Foreground blur veil, subject sharp mid-layer',
  'Frame within frame: doorway, window, screen crop',
  'Leading lines: corridor, rails, shoreline toward subject',
  'Symmetrical composition broken by one off-axis element',
  'Asymmetrical mass balance, subject off-centre calm',
  'Edge of frame clipping intentional, not centred',
  'Chin margin tight, not classic talking-head centre',
  'Lots of floor visible, subject low in frame',
  'Lots of headroom, subject low, sky or ceiling mood',
  'Crowd bokeh blobs, subject sharp isolated',
  'Single light source hard shadow graphic',
  'Soft window wrap, natural skin, no glam',
  'Neon spill one colour, skin neutral elsewhere',
  'Golden hour rim, warm fill opposite',
  'Blue hour ambient, practical lights punctuate',
  'Midday harsh sun honest, squint acceptable',
  'Overcast flat light, colour wardrobe carries interest',
  'Fog or haze layer depth between planes',
  'Rain on glass between camera and subject',
  'Snow fall streaks shallow shutter feel',
  'Dust particles in shaft of light',
  'Steam or smoke veil crossing lens lower third',
  'Speed-rail lateral move parallel to subject',
  'Pan follows moving subject, background streak',
  'Tilt from shoes up to face reveal',
  'Crash zoom subtle on reaction beat',
  'Whiplash pan settle on still subject',
  'Orbital move quarter-circle around subject',
  'Drone-height feel without drone cliché: high balcony angle',
  'CCTV high corner surveillance geometry',
  'Peephole distortion vignette subtle',
  'Fish-eye mild, environment curves playful not silly',
  'Telephoto compression, stacked background layers',
  'Wide lens close approach, mild distortion acceptable',
  'Split diopter feel: near and far both readable',
  'Lens flare controlled single streak',
  'Anamorphic streak absent; spherical honest',
  'Black frame edges vignette natural lens falloff',
  'Film grain subtle texture, not heavy',
  'Clean digital crisp, graphic shapes read',
  'Motion blur on background only, subject sharp',
  'Motion blur on subject extremities, face sharp',
  'Freeze pose tableau, then micro-motion resumes',
  'Jump-cut adjacent angle same action beat',
  'Match cut shape: round object to round light',
  'Graphic match: colour shape from cloth to sign',
  'Insert cut extreme detail then back to master',
  'Shot-reverse-shot implied in single setup turn',
  'Selfie-arm length perspective honest',
  'Tripod phone height chest level social default subverted slightly high',
  'Gimbal float smooth, not robotic',
  'Slider move one axis only, disciplined',
  'Zoom during dolly absent; pick one move only',
  'Locked focus rack later, start frame decisive focus plane',
  'Rack focus foreground to background once',
  'Deep shadow pocket, face half-lit noir-lite',
  'High key bright, clinical or cheerful',
  'Low key mostly shadow, small highlight islands',
  'Practical lamp in frame as motivated source',
  'Screen glow as key on face, room dark',
  'Silhouette against bright doorway portal',
  'Subject miniaturized in vast space',
  'Subject large in claustrophobic tight room',
  'Texture-first: fabric weave, skin pore honest, metal scratch',
  'Food steam rise crosses upper third',
  'Liquid pour arc catches light line',
  'Spark spray moment frozen mid-action',
  'Dust puff footstep read on hard light',
  'Fabric motion freeze scarf or coat edge',
  'Hair motion freeze fan or wind beat',
  'Crowd wave blur subject still anchor',
  'Vehicle passes foreground blur subject still',
  'Train window streak lights subject static inside',
  'Escalator geometry subject ascending diagonal',
  'Staircase spiral centre subject small',
  'Glass elevator city slide behind subject',
  'Bridge cable triangles frame face',
  'Tunnel mouth oval dark surround bright subject',
  'Underpass concrete texture echo subject walk',
  'Alley one-point perspective subject mid',
  'Courtyard well sky patch subject ring',
  'Balcony railing grid foreground subject beyond',
  'Fence diamond pattern bokeh subject sharp',
  'Netting sports goal pattern overlay subtle',
  'Chain link shadow stripe on face',
  'Blinds stripe shadow across scene',
  'Palm shadow dapple on skin honest',
  'Window mullion divisions cross subject careful',
  'Bookshelf grid behind subject talking',
  'Wine glass array bokeh circles',
  'String lights bokeh circles night',
  'Ferris wheel structure arc over subject',
  'Roller coaster structure triangle sky',
  'Stadium seats colour blocks empty',
  'Court lines geometry low angle',
  'Track lanes curve lead eye',
  'Pool lane lines underwater calm',
  'Sand dune ridge silhouette walk',
  'Rock face texture climber small',
  'Wave crest freeze spray crown',
  'Waterfall mist rainbow faint',
  'Canyon depth layer haze stacks',
  'Mesa flat top horizon line hard',
  'Salt flat horizon infinite subject tiny',
  'Glacier blue crack line foreground',
  'Volcanic rock black orange edge',
  'Geyser steam plume vertical column',
  'Geyser pool bacterial colour edge frame',
  'Hot spring steam blanket low subject',
  'Geyser boardwalk tourist gap honest',
  'Mangrove roots water mirror zigzag',
  'Rice terrace curve contour lines',
  'Wheat field wind wave pattern',
  'Corn maze path decision fork',
  'Pumpkin patch stem close orange',
  'Christmas tree farm row vanish',
  'Cherry blossom petal fall single beat',
  'Maple leaf pile jump mid-air',
  'Icicle row drip sun spark',
  'Frost window crystal macro subject beyond',
  'Thunderhead cloud tower distant subject small',
  'Lightning flash single frame silhouette implied not literal',
  'Aurora ribbon sky subject dark foreground',
  'Milky way arc wide tripod honest',
  'Star trail subtle not heavy',
  'Moon large telephoto subject roof line',
  'Eclipse crescent creative not scientific claim',
  'Solar flare bloom lens controlled',
  'Lens water droplet distortion macro',
  'Underwater caustic light dance floor pool',
  'Soap bubble thin-film colour macro',
  'Oil slick rainbow puddle reflection',
  'Wet asphalt reflection city lights',
  'Puddle mirror flip world subtle',
  'Broken mirror shard reflection fragment',
  'Sunglasses reflection scene cheat honest',
  'Rearview mirror face road behind',
  'Side mirror highway streak subject eye',
  'Phone screen reflection face overlay',
  'ATM screen glow numbers abstract',
  'Slot machine light chaos subject calm',
  'Neon sign letter close partial read',
  'Marquee bulb row curve bokeh',
  'Projector beam dust cone visible',
  'Stage follow-spot ellipse floor',
  'Laser line scan club haze',
  'LED wall pixel grid close moire risk avoid',
  'Hologram fan display subtle not sci-fi overload',
  'AR glasses reflection minimal not gimmick',
  'VR headset blind shell world off',
  'Motion capture dots face edge case avoid',
  'Green screen edge spill honest cleanup implied',
  'Chroma fringe absent; real location preferred',
];

/** Optional second axis for planner — short energy / pacing words. */
const PACE_ENERGY_HINTS: string[] = [
  'calm observational beat',
  'quick snappy social energy',
  'playful light humour undertone',
  'tense withheld stillness',
  'curious discovery moment',
  'routine mundane honesty',
  'small win satisfaction',
  'mild frustration micro-expression',
  'anticipation before action',
  'release after effort',
  'messy imperfect realism',
  'meticulous careful focus',
  'chaotic background calm subject',
  'calm subject chaotic hands',
  'lonely alone-not-sad mood',
  'connected intimate distance close',
  'competitive edge subtle',
  'cooperative helpful gesture',
  'surprise eyebrow flash',
  'relief exhale shoulders drop',
  'determination jaw set',
  'tired honest slump',
  'morning groggy slow',
  'night wired alert',
  'heat exhaustion wipe brow',
  'cold breath visible',
  'humid hair cling',
  'wind hair whip',
  'wet clothes cling honest',
  'dusty sleeve pat',
  'oil smudge cheek wipe',
  'paint smear hand casual',
  'flour dust cloud punch',
  'spill reaction freeze',
  'catch save reflex',
  'trip stumble recover',
  'laugh break tension',
  'awkward pause hang',
  'second take redo beat',
  'off-camera reaction listen',
  'silent communication glance',
  'loud environment lip read implied',
  'music implied not described',
  'rhythmic task repetition hypnotic',
  'single beat punchline motion',
  'slow burn setup no punchline',
  'documentary distance respectful',
  'voyeur sidewalk polite',
  'participant immersed hands busy',
  'teacher demo clarity',
  'student mistake cute',
  'expert muscle memory flow',
  'novice hesitation readable',
  'generational contrast subtle',
  'cultural specificity props honest',
  'time-of-day transition single clip implied',
  'weather shift cloud pass',
  'season cue wardrobe one item',
  'holiday cue one prop only',
  'brand-free generic packaging',
  'logo avoidance background blur',
  'screen UI illegible bokeh',
  'map unfold travel beat',
  'compass spin settle',
  'ticket tear close',
  'passport stamp implied',
  'boarding pass fold',
  'keys jingle lock approach',
  'door handle turn resistance',
  'elevator ding arrival',
  'phone buzz ignore then check',
  'watch check time pressure',
  'calendar page flip',
  'sticky note peel reveal',
  'whiteboard erase smear',
  'Highlighter stroke plan',
  'scissors snip thread',
  'needle thread squint',
  'hammer miss comedy safe',
  'sawdust puff hand plane',
  'drill torque shoulder lean',
  'solder smoke wisp vent',
  'steam wand milk swirl',
  'knife chop rhythm safe',
  'whisk blur bowl edge',
  'rolling pin dust cloud',
  'sieve shake flour snow',
  'bottle cap twist spray',
  'can tab crack hiss',
  'champagne cork implied off-screen',
  'toast clink hands close',
  'noodle slurp comic honest',
  'spice pinch macro fingers',
  'flame toss pan safe professional',
  'ice crack drink pour',
  'lemon squeeze squirt catch',
  'salt pinch crystalline macro',
  'sugar pour mound cone',
  'honey drip spiral thread',
  'butter melt spread knife',
  'bread tear steam wisp',
  'egg crack shell chips',
  'fish scale scrape honest',
  'oyster shuck twist pop',
  'crab claw crack tool',
  'corn husk peel strip',
  'apple bite crunch spray',
  'watermelon split wedge',
  'pumpkin carve tooth gap',
  'cake slice layer reveal',
  'cookie break crumbs fall',
  'ice cream drip cone race',
  'popsicle stick reveal eaten',
  'bubble gum pop cheek',
  'cotton candy dissolve pink',
  'popcorn kernel pop implied',
  'pretzel salt crystal macro',
  'nacho cheese stretch strand',
  'pizza slice cheese pull',
  'burger compress hands real',
  'taco tilt bite drip',
  'sushi chopstick lift delicate',
  'ramen chopstick lift steam',
  'pho spoon lean slurp',
  'curry tear bread dip',
  'tortilla press flatten puff',
  'wok toss flame kiss',
  'bbq tong flip char line',
  'smoker vent puff rhythm',
  'kebab skewer rotate glaze',
  'corn dog dip drip',
  'funnel cake powder snow',
  'churro sugar cloud shake',
  'donut glaze drip set',
  'croissant flake shower',
  'bagel schmear swirl',
  'pretzel knot twist geometry',
  'baguette tear crumb arc',
  'sourdough score oven spring implied',
  'pie lattice weave pattern',
  'tart brulee torch bubble',
  'macaron feet rise pastel',
  'eclair cream pipe swirl',
  'cannoli shell crack fill',
  'tiramisu dust cocoa puff',
  'crepe fold triangle plate',
  'waffle iron steam lift',
  'pancake flip mid-air',
  'oatmeal steam spoon blow',
  'cereal pour milk splash',
  'smoothie blend vortex top',
  'coffee pour latte art attempt',
  'espresso crema tiger strip',
  'tea bag dunk colour bloom',
  'matcha whisk foam micro',
  'wine swirl legs glass',
  'beer head lace lip',
  'cocktail shake frost can',
  'muddler crush herb burst',
  'peel twist citrus oil spray',
  'olive pick spear garnish',
  'cherry stem knot teeth',
  'umbrella pop rain start',
  'raincoat zipper rain run',
  'boot mud scrape mat',
  'umbrella shake droplet arc',
  'snowball pack squeeze',
  'snow angel arm sweep',
  'sandcastle drip bucket stack',
  'kite run launch stumble',
  'frisbee skip water once',
  'boomerang throw wait return',
  'jump rope double under blur',
  'hula hoop hip blur',
  'slackline wobble arms wide',
  'tightrope pole balance freeze',
  'stilts walk awkward grace',
  'unicycle idle wobble',
  'penny board carve turn',
  'longboard slide glove spark',
  'inline skate cone weave',
  'ice skate toe pick scratch',
  'roller derby pack blur',
  'parkour roll shoulder absorb',
  'backflip tuck grass stain',
  'cartwheel hands plant blur',
  'handstand shake vein honest',
  'muscle up bar clang',
  'rope climb foot lock',
  'pole climb grip burn',
  'cargo net climb sway',
  'obstacle mud splash face',
  'spartan spear throw arc',
  'archery release string snap',
  'rifle brass eject glint',
  'shotgun break load snap',
  'paintball splat mask edge',
  'airsoft bb plink tin',
  'laser tag vest vibrate implied',
  'bowling strike pin scatter',
  'curling stone sweep frantic',
  'bobsled push sprint mount',
  'luge steer subtle chin lift',
  'ski jump tuck shadow',
  'snowboard butter flex slow',
  'wakeboard rope tension spray',
  'water ski outside ski lift',
  'tube boat whip spray scream implied',
  'jet ski chop hop',
  'sail tack boom swing',
  'kayak roll bubble trail',
  'canoe J-stroke ripple',
  'paddleboard balance ripple',
  'surf duck dive board tip',
  'bodyboard spin tube',
  'snorkel mask flood clear',
  'scuba bubble regulator exhale',
  'freedive line pull descent',
  'cliff jump tuck splash wide',
  'bridge jump rope swing',
  'bungee cord stretch recoil',
  'zip line handle grip squeak',
  'rock climb crimp pain honest',
  'belay catch rope snap',
  'caving headlamp dust breath',
  'paraglider wing inflate run',
  'hang glider cliff step',
  'skydiving tandem harness check',
  'balloon basket burner roar',
  'helicopter downwash grass flat',
  'small plane prop blur start',
  'glider tow release silent',
  'drone orbit subject centre',
  'rocket launch pad steam implied stylized',
];

/**
 * Subject domain pool — WHAT the main subject is.
 * Complements SCENE_ARCHETYPE_HINTS (WHERE) and OPENING_FRAMING_HINTS (HOW framed).
 * Deliberately excludes hands, POV, and generic faces — those are the over-represented defaults.
 * 80 entries ensure wide variety across a 1000-video stream.
 */
const SUBJECT_DOMAIN_HINTS: string[] = [
  // Animals
  'a bird perched or mid-flight',
  'a cat stretching or grooming',
  'a dog running through open space',
  'a bee landing on a flower',
  'a butterfly opening its wings',
  'a fish moving through clear water',
  'a squirrel mid-leap or foraging',
  'a snail on a wet surface',
  'a spider spinning web threads',
  'a frog resting on a leaf',
  // Plants and nature
  'a single flowering branch',
  'moss covering wet stone',
  'a sunflower tracking light',
  'tall grass moving in wind',
  'a seed sprouting through soil',
  'autumn leaves mid-fall',
  'a cactus in harsh light',
  'lichen on old rock surface',
  'a dandelion releasing seeds',
  'ivy climbing an old wall',
  // Food and drink
  'a steaming cup of coffee or tea',
  'bread being torn open fresh',
  'noodles being lifted with chopsticks',
  'fruit being sliced or bitten',
  'honey dripping from a spoon',
  'ice melting in a glass',
  'batter being poured into a pan',
  'pasta being twirled on a fork',
  'a knife chopping fresh herbs',
  'bubbles rising in a carbonated drink',
  // Objects and craft
  'a spinning vinyl record',
  'an old clock mechanism turning',
  'a typewriter key being pressed',
  'thread being woven on a loom',
  'ceramic being shaped on a wheel',
  'a paint roller covering a wall',
  'a pen writing on paper',
  'scissors cutting through fabric',
  'a match being struck',
  'wax dripping from a candle',
  // Nature elements
  'water surface with spreading ripples',
  'a candle flame in still air',
  'a soap bubble forming or floating',
  'smoke drifting slowly upward',
  'sand flowing through a gap',
  'snow settling on a surface',
  'rain hitting a puddle or glass',
  'fire crackling in a hearth',
  'fog rolling across low ground',
  'a shadow moving across a surface',
  // Architecture and texture
  'worn brick wall with peeling paint',
  'a painted wood door with texture',
  'rusted metal with colour and pattern',
  'cracked pavement with weeds pushing through',
  'old tiles with chipped glaze',
  'a staircase ascending into light',
  'a window casting a geometric shadow',
  'a bridge railing with city behind',
  'a rooftop with sky above',
  'an old door handle or lock',
  // Movement and objects in motion
  'a bicycle wheel spinning freely',
  'laundry hanging on a line in breeze',
  'a paper airplane mid-flight',
  'a kite pulling against the wind',
  'a ball bouncing or rolling',
  'a coin spinning on a surface',
  'a pendulum swinging',
  'a flag rippling in wind',
  'a balloon drifting upward',
  'an umbrella opening in rain',
  // People (non-hands, non-face, non-POV)
  "a person's feet walking on pavement or grass",
  "someone's back or silhouette against light",
  'a figure moving in the distance',
  'legs dangling from a high ledge or branch',
  'a person lying in grass or on a rooftop',
  'a child running seen from behind',
  'a dancer from the waist down only',
  'someone reflected in still water',
  'a person reading, face obscured by book',
  'hair blowing across a face in wind',
];

async function slotHash32(streamId: string, batchIndex: number, sequenceNum: number): Promise<number> {
  const hex = await sha256Hex(`${streamId}|${batchIndex}|${sequenceNum}`);
  return parseInt(hex.slice(0, 8), 16) >>> 0;
}

/**
 * Deterministic hints for one job slot. Returns null if diversity off.
 *
 * plannerLines now includes THREE mandatory dimensions:
 *   1. Scene archetype — WHERE the video takes place (228-entry pool)
 *   2. Subject domain  — WHAT the main subject is (80-entry pool, no hands/POV bias)
 *   3. Pace/energy     — HOW IT FEELS (200-entry pool; always in full, 50/50 in soft)
 */
export async function stableSlotHints(
  streamId: string,
  batchIndex: number,
  sequenceNum: number,
  mode: DiversityMode,
): Promise<SlotHints | null> {
  if (mode === 'off') return null;

  const h = await slotHash32(streamId, batchIndex, sequenceNum);
  const iArc  = h % SCENE_ARCHETYPE_HINTS.length;
  const iOpen = (Math.imul(h, 2654435761) >>> 0) % OPENING_FRAMING_HINTS.length;
  const iPace = (h >>> 16) % PACE_ENERGY_HINTS.length;
  const iSubj = (Math.imul(h, 1597334677) >>> 0) % SUBJECT_DOMAIN_HINTS.length;

  const archetype    = SCENE_ARCHETYPE_HINTS[iArc]!;
  const opening      = OPENING_FRAMING_HINTS[iOpen]!;
  const pace         = PACE_ENERGY_HINTS[iPace]!;
  const subjectDomain = SUBJECT_DOMAIN_HINTS[iSubj]!;

  if (mode === 'soft') {
    const addPace = (h & 2) === 0;
    const plannerLines = addPace
      ? `${archetype} Main subject: ${subjectDomain}. Overall energy: ${pace}.`
      : `${archetype} Main subject: ${subjectDomain}.`;
    return {
      plannerLines,
      rendererFrameEmphasis: opening,
    };
  }

  // full
  return {
    plannerLines: `${archetype} Main subject: ${subjectDomain}. Pacing feel: ${pace}.`,
    rendererFrameEmphasis: opening,
  };
}
