/**
 * Prompt renderer — passthrough for the merged single-call planner.
 *
 * The prompt paragraph is now generated inside generateBrief() in a single
 * Gemini call. This function exists only for backward-compat with pipeline.ts
 * callers and adds zero subrequest cost.
 */

import type { GeminiConfig } from './gemini.js';
import type { PromptBrief } from './planner.js';

export async function renderPrompt(
  brief: PromptBrief,
  _durationSecs: number,
  _config: GeminiConfig,
  _frameEmphasis?: string | null,
): Promise<string> {
  // Prompt is already fully generated by the planner in a single Gemini call.
  // No additional LLM call — preserves subrequest budget and halves quota burn.
  return brief.prompt;
}
